// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezdrejfhqtdeercncial.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZHJlamZocXRkZWVyY25jaWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDAwMTksImV4cCI6MjA2OTgxNjAxOX0.ciy3zwvRIOxgvL_7ni_sP4BgDUziGSJH0ONuXi5Fkus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});